### ISSUE TITLE
Upgrade to Python 3.11 (3.12 will be in another opportunity)

### ISSUE THREAD

**Issue by viniarck** [kytos-ng/kytos#448]
This supersedes https://github.com/kytos-ng/kytos/issues/309

In a next opportunity probably on `2024.1` let's see if we'll can afford:

- Upgrade to Python 3.11
- Update certain core dependencies (openapi-core + potentially others too)
- Update [Kytos-ng how to setup env with 3.11](https://github.com/kytos-ng/documentation/blob/master/tutorials/napps/development_environment_setup.rst)
- Make sure unit tests and e2e are still passing

When this gets prioritized this deserves its own epic, and tasks will be further broken down.

**Comment by viniarck** [comment]
core libs to potentially ugrade if no blockers:

- `pymongo==4.6.1`
- `elastic-apm==6.20.0`
- `starlette[full]==0.37.1`
- `uvicorn[standard]==0.27.1`
- `asgiref==3.7.2`
- `openapi-core==0.19.0`
- `httpx==0.26.0`
- `ipython==8.21.0`
- `jinja==3.1.3`
- `watchdog==4.0.0`
- `pyjwt==2.8.0`
- `dnspython==2.6.1`
- `tenacity==8.2.3`


related issues:

https://github.com/kytos-ng/kytos/issues/350

https://github.com/kytos-ng/kytos/issues/420

**Comment by viniarck** [comment]
When upgrading to python 3.12 it also needs to be updated on Scrutinizer CI, here's the current template, we'll need to bump the version when the time comes, but if locally tests are passing it should pass on CI too, so you won't be blocked as you work on this locally:

```
checks:
    python:
        code_rating: true
        duplicate_code: true
filter:
    paths: ['*']
build:
    environment:
        python: 3.9.12
        postgresql: false
        redis: false
    dependencies:
        before:
            - pip install tox==3.27.1 virtualenv==20.21.0 coverage
    tests:
        override:
            -
                command: 'tox'
                idle_timeout: 300
                coverage:
                    file: '.coverage'
                    config_file: '.coveragerc'
                    format: 'py-cc'
    nodes:
        analysis:
            tests:
                override:
                    - py-scrutinizer-run
        tests: true
```
